In [ ]:
import numpy as np 

In [ ]:
'''A. Create arrays 
create the following arrays
1) one dimension A : [1,4,5,6]
2) two dimension: (2 rows, 4 columns )  
3) two dimension: an array of 3 rows of the array in (1)
4) 3-dimension array with shape (2,3,4)
5) 1-dim array of size 10 and all values are 1 
6) 2-dim array(2,3) and cells' values are real numbers in [5,19]
7) 2-dim array(2,3) and values are integers of [10,20] 
'''

"A. Create arrays \ncreate the following arrays\n1) one dimension A : [1,4,5,6]\n2) two dimension: (2 rows, 4 columns )  \n3) two dimension: an array of 3 rows of the array in (1)\n4) 3-dimension array with shape (2,3,4)\n5) 1-dim array of size 10 and all values are 1 \n6) 2-dim array(2,3) and cells' values are real numbers in [5,19]\n7) 2-dim array(2,3) and values are integers of [10,20] \n"

In [2]:
import numpy as np

In [14]:
A=np.array([1,4,5,6])
print("1) ", A, "\n")

B=np.array([[1,2,3,4], [5,6,7,8]])
print("2) ", B, "\n" )

C=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("3) ", C, "\n")

D=np.zeros((2,3,4))
print("4) ", D, "\n")

E=np.array(10*[1])
print("5) ", E, "\n")

F=np.random.uniform(5,19,size=(2,3))
print("6) ", F, "\n")

G=np.random.uniform(10,20,size=(2,3))
print("6) ", G, "\n")

1)  [1 4 5 6] 

2)  [[1 2 3 4]
 [5 6 7 8]] 

3)  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

4)  [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 

5)  [1 1 1 1 1 1 1 1 1 1] 

6)  [[15.42300421 16.8689563   8.49018885]
 [13.28725221  6.34939254  7.30787645]] 

6)  [[13.20652655 10.49709477 15.18592505]
 [19.50575546 16.61112286 13.30340238]] 



In [ ]:

'''
B. shape and reshape
1) create a 2-dim array and show its shape: call it A
- get row number of A
- get col number of A
2) create a 3-dim array and show its shape: call it B
3) convert A to 1-dim array
4) convert A to 2-dim array with k rows (choose a suitable k for shape of A)
5) create an 1-dim array and convert it to 2-dim array with shape(m,n)
'''

In [29]:
A= np.array([[1,2,3,4], [5,6,7,8]])
rowA= len(A)
colA=len(A[0])

print("1) ", A)
print("rowA= ", rowA)
print("colA= ", colA)
A.shape

print()
B=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print("2) ", B)
B.shape

print()
C=A.flatten()
print("3) ", C)

print()
D=np.reshape(C,(4,-1))
print("4) ", D)

print()
m=2
n=3
E=np.array([1,2,3,4,5,6])
print("5) ", E)
E.reshape(m,n)



1)  [[1 2 3 4]
 [5 6 7 8]]
rowA=  2
colA=  4

2)  [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

3)  [1 2 3 4 5 6 7 8]

4)  [[1 2]
 [3 4]
 [5 6]
 [7 8]]

5)  [1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
'''
C. Indexing and Slicing for selecting elements or sub-array 
1) create an 1-dim array [1 2 .. 100] 
- get sub-array containing 20 first elements
- get sub-array containing 20 last elements
- get sub-array containing elements of index m to n (note: m, n get values from users)
2) create an matrix A like
[ 1 2 3 4 5
  6 7 8 9 10
]
- get B, C are sub-matrice of A such that:
a) B = 
[ 1 2 3 4
  6 7 8 9
] 
C = 
[ 5
  10
]
b) B = 
[ 2 3
  7 8  
]
'''


'\nC. Indexing and Slicing for selecting elements or sub-array \n1) create an 1-dim array [1 2 .. 100] \n- get sub-array containing 20 first elements\n- get sub-array containing 20 last elements\n- get sub-array containing elements of index m to n (note: m, n get values from users)\n2) create an matrix A like\n[ 1 2 3 4 5\n  6 7 8 9 10\n]\n- get B, C are sub-matrice of A such that:\na) B = \n[ 1 2 3 4\n  6 7 8 9\n] \nC = \n[ 5\n  10\n]\nb) B = \n[ 2 3\n  7 8  \n]\n'

In [53]:
print()
A=np.arange(1,101)
print("1) ", A)

print()
print("sub-array containing 20 first elements: ")
print(A[:20])

print()
print("sub-array containing 20 last elements ")
print(A[80:])

print()
print("sub-array containing elements of index m=5 to n=20 ")
print(A[5:20])

print()
K=np.array([[1,2,3,4,5],[6,7,8,9,10]])
B=K[0:4, 0:4]
C=np.array([K[0,4], K[1,4]])
D=np.array([K[0][1:3],K[1][1:3]])

print("K= ", K)
print("B= ", B)
print("C= ", C)
print("D= ", D)




1)  [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

sub-array containing 20 first elements: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

sub-array containing 20 last elements 
[ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
  99 100]

sub-array containing elements of index m=5 to n=20 
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

K=  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
B=  [[1 2 3 4]
 [6 7 8 9]]
C=  [ 5 10]
D=  [[2 3]
 [7 8]]


In [ ]:
'''
D. Operation on multiple matrices
Create two matrices 
a = [ 1 1 1 1
      1 2 3 4 ]
b = [ 2 2 2 2
      1 2 3 4 ]
1) multiply a and b
2) dot a and b.T
3) concatenate a and b by rows
c= [  1 1 1 1
      1 2 3 4 
      2 2 2 2
      1 2 3 4 ]

4) concatenate a and b by columns
c= [  1 1 1 1 2 2 2 2
      1 2 3 4 1 2 3 4 ]
5) concatenate a with the last column of b
'''


'\nD. Operation on multiple matrices\nCreate two matrices \na = [ 1 1 1 1\n      1 2 3 4 ]\nb = [ 2 2 2 2\n      1 2 3 4 ]\n1) multiply a and b\n2) dot a and b.T\n3) concatenate a and b by rows\nc= [  1 1 1 1\n      1 2 3 4 \n      2 2 2 2\n      1 2 3 4 ]\n\n4) concatenate a and b by columns\nc= [  1 1 1 1 2 2 2 2\n      1 2 3 4 1 2 3 4 ]\n5) concatenate a with the last column of b\n'

In [72]:
A = np.array([[1,1,1,1], [1,2,3,4]])
B = np.array([[2,2,2,2], [1,2,3,4]])
T = np.array([9,8,7,6])
T.shape

print()
print("A= ", A)
print()
print("B= ", B)


print("Không thể nhân 2 ma trận có kích thước 2x4 với 2x4")

K=np.dot(A,T)
print()
print("A dot T: ", K)

L=np.dot(B,T)
print()
print("B dot T: ", L)

C1= np.concatenate((A,B))
print()
print("C1: ", C1)

C2= np.concatenate((A,B), axis=1)
print()
print("C2: ", C2)


A=  [[1 1 1 1]
 [1 2 3 4]]

B=  [[2 2 2 2]
 [1 2 3 4]]
Không thể nhân 2 ma trận có kích thước 2x4 với 2x4

A dot T:  [30 70]

B dot T:  [60 70]

C1:  [[1 1 1 1]
 [1 2 3 4]
 [2 2 2 2]
 [1 2 3 4]]

C2:  [[1 1 1 1 2 2 2 2]
 [1 2 3 4 1 2 3 4]]


In [ ]:
'''
E. Operation with condition 
1) given an 1-dim array A = [1 2 3 5 7 4]
- remove all odd numbers in A
- get array B by removing elements so that their indexs of even numbers 
2) given two 1-dim arrays, 
- get the intersection of them
- get the union of them 
'''


'\nE. Operation with condition \n1) given an 1-dim array A = [1 2 3 5 7 4]\n- remove all odd numbers in A\n- get array B by removing elements so that their indexs of even numbers \n2) given two 1-dim arrays, \n- get the intersection of them\n- get the union of them \n'

In [77]:
A=np.array([1,2,3,5,7,4])
find= [x for x in A if x%2==0]
print("A= ", A)
print()
print("find= ", find)

C1=[1,2,3,9,8,7,6,5,4]
C2=[1,5,2,7,15,12,11]
print("C1= ", C1)
print()
print("C2= ", C2)
print()

C3= np.intersect1d(C1,C2)
print("C3= ", C3)
print()

C4= np.union1d(C1,C2)
print("C4= ", C4)
print()


A=  [1 2 3 5 7 4]

find=  [2, 4]
C1=  [1, 2, 3, 9, 8, 7, 6, 5, 4]

C2=  [1, 5, 2, 7, 15, 12, 11]

C3=  [1 2 5 7]

C4=  [ 1  2  3  4  5  6  7  8  9 11 12 15]



In [ ]:
a = np.array([1,2,3,5,7,4])
b = [x for x in a if x%2==1]
print(b)

[1, 3, 5, 7]
