In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving post-operative.data to post-operative.data


In [3]:
import pandas as pd
import io

dataframe = pd.read_csv(io.StringIO(uploaded['post-operative.data'].decode('utf-8')), names=["L-CORE", "L-SURF", "L-O2", "L-BP", "SURF-STBL", "CORE-STBL", "BP-STBL", "COMFORT", "ADM-DECS"])
dataframe

L-CORE L-SURF       L-O2  L-BP  ... CORE-STBL     BP-STBL COMFORT ADM-DECS
0     mid    low  excellent   mid  ...    stable      stable      15        A
1     mid   high  excellent  high  ...    stable      stable      10        S
2    high    low  excellent  high  ...    stable  mod-stable      10        A
3     mid    low       good  high  ...  unstable  mod-stable      15       A 
4     mid    mid  excellent  high  ...    stable      stable      10        A
..    ...    ...        ...   ...  ...       ...         ...     ...      ...
85    mid    mid  excellent   mid  ...    stable      stable      10        A
86    mid    mid  excellent   mid  ...    stable      stable      15        S
87    mid    mid       good   mid  ...    stable      stable      15        A
88    mid    mid  excellent   mid  ...    stable      stable      10        A
89    mid    mid       good   mid  ...    stable      stable      15        S

[90 rows x 9 columns]

In [4]:
index=0
print('Các dòng bị missing data: ')
for row in dataframe.itertuples():
  for column in row:
    if column=='?':
      print(index)
  index = index+1

Các dòng bị missing data: 
46
48
70


In [5]:
dataframe1=dataframe
dataframe1

L-CORE L-SURF       L-O2  L-BP  ... CORE-STBL     BP-STBL COMFORT ADM-DECS
0     mid    low  excellent   mid  ...    stable      stable      15        A
1     mid   high  excellent  high  ...    stable      stable      10        S
2    high    low  excellent  high  ...    stable  mod-stable      10        A
3     mid    low       good  high  ...  unstable  mod-stable      15       A 
4     mid    mid  excellent  high  ...    stable      stable      10        A
..    ...    ...        ...   ...  ...       ...         ...     ...      ...
85    mid    mid  excellent   mid  ...    stable      stable      10        A
86    mid    mid  excellent   mid  ...    stable      stable      15        S
87    mid    mid       good   mid  ...    stable      stable      15        A
88    mid    mid  excellent   mid  ...    stable      stable      10        A
89    mid    mid       good   mid  ...    stable      stable      15        S

[90 rows x 9 columns]

In [6]:
dataframe1=dataframe1.drop(labels=[46,48,70], axis=0)
dataframe1

L-CORE L-SURF       L-O2  L-BP  ... CORE-STBL     BP-STBL COMFORT ADM-DECS
0     mid    low  excellent   mid  ...    stable      stable      15        A
1     mid   high  excellent  high  ...    stable      stable      10        S
2    high    low  excellent  high  ...    stable  mod-stable      10        A
3     mid    low       good  high  ...  unstable  mod-stable      15       A 
4     mid    mid  excellent  high  ...    stable      stable      10        A
..    ...    ...        ...   ...  ...       ...         ...     ...      ...
85    mid    mid  excellent   mid  ...    stable      stable      10        A
86    mid    mid  excellent   mid  ...    stable      stable      15        S
87    mid    mid       good   mid  ...    stable      stable      15        A
88    mid    mid  excellent   mid  ...    stable      stable      10        A
89    mid    mid       good   mid  ...    stable      stable      15        S

[87 rows x 9 columns]

In [7]:
X = dataframe1.values[:,:-1]
y = dataframe1.values[:,-1]
print(X)
print(y)

[['mid' 'low' 'excellent' 'mid' 'stable' 'stable' 'stable' '15']
 ['mid' 'high' 'excellent' 'high' 'stable' 'stable' 'stable' '10']
 ['high' 'low' 'excellent' 'high' 'stable' 'stable' 'mod-stable' '10']
 ['mid' 'low' 'good' 'high' 'stable' 'unstable' 'mod-stable' '15']
 ['mid' 'mid' 'excellent' 'high' 'stable' 'stable' 'stable' '10']
 ['high' 'low' 'good' 'mid' 'stable' 'stable' 'unstable' '15']
 ['mid' 'low' 'excellent' 'high' 'stable' 'stable' 'mod-stable' '05']
 ['high' 'mid' 'excellent' 'mid' 'unstable' 'unstable' 'stable' '10']
 ['mid' 'high' 'good' 'mid' 'stable' 'stable' 'stable' '10']
 ['mid' 'low' 'excellent' 'mid' 'unstable' 'stable' 'mod-stable' '10']
 ['mid' 'mid' 'good' 'mid' 'stable' 'stable' 'stable' '15']
 ['mid' 'low' 'good' 'high' 'stable' 'stable' 'mod-stable' '10']
 ['high' 'high' 'excellent' 'high' 'unstable' 'stable' 'unstable' '15']
 ['mid' 'high' 'good' 'mid' 'unstable' 'stable' 'mod-stable' '10']
 ['mid' 'low' 'good' 'high' 'unstable' 'unstable' 'stable' '15']


In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for i in range(X.shape[1]):
    X[:,i] = encoder.fit_transform(X[:,i], )
print(X)

[[2 1 0 2 0 1 1 3]
 [2 0 0 0 0 1 1 2]
 [0 1 0 0 0 1 0 2]
 [2 1 1 0 0 2 0 3]
 [2 2 0 0 0 1 1 2]
 [0 1 1 2 0 1 2 3]
 [2 1 0 0 0 1 0 0]
 [0 2 0 2 1 2 1 2]
 [2 0 1 2 0 1 1 2]
 [2 1 0 2 1 1 0 2]
 [2 2 1 2 0 1 1 3]
 [2 1 1 0 0 1 0 2]
 [0 0 0 0 1 1 2 3]
 [2 0 1 2 1 1 0 2]
 [2 1 1 0 1 2 1 3]
 [0 0 0 0 1 1 2 2]
 [1 0 1 0 1 1 0 3]
 [2 1 1 0 1 1 1 2]
 [2 0 1 2 1 1 2 3]
 [2 2 1 2 0 1 1 2]
 [1 0 1 2 1 1 1 3]
 [1 2 0 0 1 1 2 2]
 [2 2 1 2 1 1 2 3]
 [2 2 1 2 1 1 1 2]
 [0 0 1 2 0 1 0 2]
 [1 2 1 2 1 1 1 2]
 [0 2 1 1 0 1 0 2]
 [1 2 0 0 0 1 0 2]
 [2 2 0 2 0 1 2 3]
 [2 2 1 2 1 1 2 2]
 [2 2 1 0 1 1 1 2]
 [1 1 1 2 1 1 2 2]
 [2 2 0 0 1 1 0 2]
 [2 1 1 2 0 1 1 2]
 [1 2 0 0 0 1 0 2]
 [2 2 1 2 0 1 1 2]
 [1 2 0 2 0 1 1 2]
 [1 1 1 2 1 1 2 2]
 [1 1 1 2 0 1 1 1]
 [2 2 1 0 1 1 0 2]
 [1 1 1 2 1 1 1 2]
 [1 2 1 2 0 1 1 3]
 [0 0 1 0 1 1 1 3]
 [2 2 1 2 0 1 1 2]
 [1 1 0 2 0 1 1 2]
 [1 2 1 2 1 1 1 2]
 [2 2 0 2 1 1 1 2]
 [2 0 1 1 1 1 1 2]
 [2 0 1 2 1 0 0 2]
 [1 0 0 2 1 1 1 2]
 [2 1 0 0 1 1 2 2]
 [2 2 1 2 1 1 0 2]
 [0 0 0 2 1 

In [9]:
X=np.array(X, dtype=np.float32)
X

array([[2., 1., 0., 2., 0., 1., 1., 3.],
       [2., 0., 0., 0., 0., 1., 1., 2.],
       [0., 1., 0., 0., 0., 1., 0., 2.],
       [2., 1., 1., 0., 0., 2., 0., 3.],
       [2., 2., 0., 0., 0., 1., 1., 2.],
       [0., 1., 1., 2., 0., 1., 2., 3.],
       [2., 1., 0., 0., 0., 1., 0., 0.],
       [0., 2., 0., 2., 1., 2., 1., 2.],
       [2., 0., 1., 2., 0., 1., 1., 2.],
       [2., 1., 0., 2., 1., 1., 0., 2.],
       [2., 2., 1., 2., 0., 1., 1., 3.],
       [2., 1., 1., 0., 0., 1., 0., 2.],
       [0., 0., 0., 0., 1., 1., 2., 3.],
       [2., 0., 1., 2., 1., 1., 0., 2.],
       [2., 1., 1., 0., 1., 2., 1., 3.],
       [0., 0., 0., 0., 1., 1., 2., 2.],
       [1., 0., 1., 0., 1., 1., 0., 3.],
       [2., 1., 1., 0., 1., 1., 1., 2.],
       [2., 0., 1., 2., 1., 1., 2., 3.],
       [2., 2., 1., 2., 0., 1., 1., 2.],
       [1., 0., 1., 2., 1., 1., 1., 3.],
       [1., 2., 0., 0., 1., 1., 2., 2.],
       [2., 2., 1., 2., 1., 1., 2., 3.],
       [2., 2., 1., 2., 1., 1., 1., 2.],
       [0., 0., 

In [10]:
y=encoder.fit_transform(y)
y

array([0, 3, 0, 1, 0, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3,
       0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 3,
       0, 3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0,
       0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 0, 0, 3, 2, 0, 0, 0, 3, 0, 0, 3])

In [44]:
from math import exp

def sigmoid(z):
  return 1.0/(1.0 + np.exp(-z))

def sigmoid_prime(z):
  return sigmoid(z)*(1-sigmoid(z))

class NN:

  def __init__(self, l):

    self.weights = []
        # Set giá trị weight tương ứng cho input layer và hidden layer random
    for i in range(1, len(l) - 1):
      w = 2*np.random.random((l[i-1] + 1, l[i] + 1)) -1
      self.weights.append(w)

    # Set giá trị weight tương ứng của out layer random
    w = 2*np.random.random( (l[i] + 1, l[i+1])) - 1
    self.weights.append(w)

  def fit(self, X, y, text_size=0.2, epochs=10000):
    # Một Epoch được tính là khi chúng ta đưa tất cả dữ liệu vào mạng neural network 1 lần. đem toàn bộ dữ liệu qua mạng một vài lần để tìm được kết quả tối ưu
    #Thêm giá trị bias vào input layer
    bias = np.atleast_2d(np.ones(X.shape[0]))
    X = np.concatenate((bias.T, X), axis=1)
         
    for i in range(epochs):
      k = np.random.randint(X.shape[0])
      v = [X[k]]

      for l in range(len(self.weights)):
        dot_value = np.dot(v[l], self.weights[l])
        activation = sigmoid(dot_value)
        v.append(activation)

      #Tầng output
      error = y[k] - v[-1]
      delta = [error * sigmoid_prime(v[-1])]

      #Bắt đầu từ lớp thứ 2 tới lớp cuối cùng
      for l in range(len(v) - 2, 0, -1): 
        delta.append(delta[-1].dot(self.weights[l].T)*sigmoid_prime(v[l]))

      # reverse [leve43(output)->leve42(hidden)]  => [leve42(hidden)->leve43(output)]
      delta.reverse()

      #Gradient descent:
        # 1. Nhân delta đầu ra của nó và kích hoạt đầu vào để lấy gradient của trọng lượng.
        # 2. Trừ một tỷ lệ (phần trăm) của gradient khỏi trọng lượng
      for i in range(len(self.weights)):
        layer = np.atleast_2d(v[i])
        deltai = np.atleast_2d(delta[i])
        self.weights[i] += text_size * layer.T.dot(deltai)

  def predict(self, x): 
    b = np.concatenate((np.ones(1).T, np.array(x)))      
    for l in range(0, len(self.weights)):
      b = sigmoid(np.dot(b, self.weights[l]))
    return b

nn = NN([8,50,1])   
nn.fit(X, y)
for e in X:
  print(e,nn.predict(e))


[2. 1. 0. 2. 0. 1. 1. 3.] [0.50319527]
[2. 0. 0. 0. 0. 1. 1. 2.] [0.45682052]
[0. 1. 0. 0. 0. 1. 0. 2.] [0.48647431]
[2. 1. 1. 0. 0. 2. 0. 3.] [0.51868256]
[2. 2. 0. 0. 0. 1. 1. 2.] [0.50619932]
[0. 1. 1. 2. 0. 1. 2. 3.] [0.999864]
[2. 1. 0. 0. 0. 1. 0. 0.] [0.96926693]
[0. 2. 0. 2. 1. 2. 1. 2.] [1.]
[2. 0. 1. 2. 0. 1. 1. 2.] [0.7701194]
[2. 1. 0. 2. 1. 1. 0. 2.] [0.56067402]
[2. 2. 1. 2. 0. 1. 1. 3.] [0.50901582]
[2. 1. 1. 0. 0. 1. 0. 2.] [0.52715721]
[0. 0. 0. 0. 1. 1. 2. 3.] [0.34938742]
[2. 0. 1. 2. 1. 1. 0. 2.] [0.65993342]
[2. 1. 1. 0. 1. 2. 1. 3.] [0.50698514]
[0. 0. 0. 0. 1. 1. 2. 2.] [0.37828822]
[1. 0. 1. 0. 1. 1. 0. 3.] [0.44422246]
[2. 1. 1. 0. 1. 1. 1. 2.] [0.50760784]
[2. 0. 1. 2. 1. 1. 2. 3.] [0.50207337]
[2. 2. 1. 2. 0. 1. 1. 2.] [0.9999762]
[1. 0. 1. 2. 1. 1. 1. 3.] [0.50709388]
[1. 2. 0. 0. 1. 1. 2. 2.] [0.49718297]
[2. 2. 1. 2. 1. 1. 2. 3.] [0.50274559]
[2. 2. 1. 2. 1. 1. 1. 2.] [0.97591871]
[0. 0. 1. 2. 0. 1. 0. 2.] [1.]
[1. 2. 1. 2. 1. 1. 1. 2.] [1.]
[0. 2. 1. 1. 0