In [2]:
import numpy as np
import pandas as pd

In [35]:
from google.colab import files
uploaded = files.upload()

Saving adult.data to adult.data
Saving adult_test.data to adult_test.data


1. age: continuous
2. workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
3. fnlwgt: continuous.
4. education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
5. education-num: continuous.
6. marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
7. occupation: Tech-support, Craft-repair, Other-service, Sales Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv Protective-serv, Armed-Forces.
8. relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
9. race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
10. sex: Female, Male.
11. capital-gain: continuous.
12. capital-loss: continuous.
13. hours-per-week: continuous.
14. native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
15. salary: determine whether a person makes over 50K a year

In [36]:
import io

dataframe = pd.read_csv(io.StringIO(uploaded['adult.data'].decode('utf-8')), names=["age", "workclass", "fnlwgt", "education", "education-num", "marital-status",
                                                                                   "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss",
                                                                                   "hours-per-week", "native-country", "salary"])
dataframe


age          workclass  fnlwgt  ... hours-per-week  native-country  salary
0       39          State-gov   77516  ...             40   United-States   <=50K
1       50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2       38            Private  215646  ...             40   United-States   <=50K
3       53            Private  234721  ...             40   United-States   <=50K
4       28            Private  338409  ...             40            Cuba   <=50K
...    ...                ...     ...  ...            ...             ...     ...
32556   27            Private  257302  ...             38   United-States   <=50K
32557   40            Private  154374  ...             40   United-States    >50K
32558   58            Private  151910  ...             40   United-States   <=50K
32559   22            Private  201490  ...             20   United-States   <=50K
32560   52       Self-emp-inc  287927  ...             40   United-States    >50K

[32561 rows x 15 columns]

In [37]:
x= dataframe.values[:, :-1]
y= dataframe.values[:, -1]
print(x)
print(y)

[[39 ' State-gov' 77516 ... 0 40 ' United-States']
 [50 ' Self-emp-not-inc' 83311 ... 0 13 ' United-States']
 [38 ' Private' 215646 ... 0 40 ' United-States']
 ...
 [58 ' Private' 151910 ... 0 40 ' United-States']
 [22 ' Private' 201490 ... 0 20 ' United-States']
 [52 ' Self-emp-inc' 287927 ... 0 40 ' United-States']]
[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' >50K']


In [38]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for i in range (x.shape[1]):
    x[:, i]= encoder.fit_transform(x[:,i])
print(x)

[[22 7 2671 ... 0 39 39]
 [33 6 2926 ... 0 12 39]
 [21 4 14086 ... 0 39 39]
 ...
 [41 4 7883 ... 0 39 39]
 [5 4 12881 ... 0 19 39]
 [35 5 17825 ... 0 39 39]]


In [55]:
x_train = x[:32559, :]
y_train = y[:32559]
x_test = x[32559:,:]
y_test=y[32559:]

In [56]:
from sklearn.naive_bayes import MultinomialNB
model_NB=MultinomialNB()
model_NB.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [57]:
y_pred=model_NB.predict(x_test)
print(y_pred)
print(y_test)

[' <=50K' ' >50K']
[' <=50K' ' >50K']


In [58]:
from sklearn.naive_bayes import GaussianNB
model_NB2=GaussianNB()
model_NB2.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [59]:
y_pred2=model_NB2.predict(x_test)
print(y_pred2)
print(y_test)

[' <=50K' ' >50K']
[' <=50K' ' >50K']


In [60]:
from sklearn.naive_bayes import BernoulliNB
model_NB3=BernoulliNB()
model_NB3.fit(x_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [61]:
y_pred3=model_NB3.predict(x_test)
print(y_pred3)
print(y_test)

[' <=50K' ' <=50K']
[' <=50K' ' >50K']
