In [2]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving computer.csv to computer.csv


In [4]:
import io

dataframe = pd.read_csv(io.StringIO(uploaded['computer.csv'].decode('utf-8')))
dataframe

Age  Income Student Credit_rating  Buy
0     30<=    high      no          fair   no
1     30<=    high      no     excellent   no
2   31..40    high      no          fair  yes
3      40>  medium     yes          fair  yes
4      40>     low     yes          fair  yes
5      40>     low     yes     excellent   no
6   31..40     low      no     excellent  yes
7     30<=  medium      no          fair   no
8     30<=     low     yes          fair  yes
9      40>  medium     yes          fair  yes
10    30<=  medium     yes     excellent  yes
11  31..40  medium      no     excellent  yes
12  31..40    high     yes          fair  yes
13     40>  medium      no     excellent   no

In [7]:
x= dataframe.values[:, :-1]
y= dataframe.values[:, -1]
print(x)
print(y)

[['30<=' 'high' 'no' 'fair']
 ['30<=' 'high' 'no' 'excellent']
 ['31..40' 'high' 'no' 'fair']
 ['40>' 'medium' 'yes' 'fair']
 ['40>' 'low' 'yes' 'fair']
 ['40>' 'low' 'yes' 'excellent']
 ['31..40' 'low' 'no' 'excellent']
 ['30<=' 'medium' 'no' 'fair']
 ['30<=' 'low' 'yes' 'fair']
 ['40>' 'medium' 'yes' 'fair']
 ['30<=' 'medium' 'yes' 'excellent']
 ['31..40' 'medium' 'no' 'excellent']
 ['31..40' 'high' 'yes' 'fair']
 ['40>' 'medium' 'no' 'excellent']]
['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']


In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for i in range (x.shape[1]):
    x[:, i]= encoder.fit_transform(x[:,i])
print(x)

[[0 0 0 1]
 [0 0 0 0]
 [1 0 0 1]
 [2 2 1 1]
 [2 1 1 1]
 [2 1 1 0]
 [1 1 0 0]
 [0 2 0 1]
 [0 1 1 1]
 [2 2 1 1]
 [0 2 1 0]
 [1 2 0 0]
 [1 0 1 1]
 [2 2 0 0]]


In [13]:
x_train = x[:12, :]
y_train = y[:12]
x_test = x[12:,:]
y_test=y[12:]

In [14]:
from sklearn.naive_bayes import MultinomialNB
model_NB=MultinomialNB()
model_NB.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [15]:
y_pred=model_NB.predict(x_test)
print(y_pred)
print(y_test)

['yes' 'yes']
['yes' 'no']


In [16]:
from sklearn.naive_bayes import GaussianNB
model_NB2=GaussianNB()
model_NB2.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [18]:
y_pred2=model_NB2.predict(x_test)
print(y_pred2)
print(y_test)

['yes' 'yes']
['yes' 'no']


In [19]:
from sklearn.naive_bayes import BernoulliNB
model_NB3=BernoulliNB()
model_NB3.fit(x_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [20]:
y_pred3=model_NB2.predict(x_test)
print(y_pred3)
print(y_test)

['yes' 'yes']
['yes' 'no']


In [21]:
x_test1 = x[:12, :]
y_test1 = y[:12]
x_train1 = x[12:,:]
y_train1=y[12:]