In [2]:
import numpy as np
import pandas as pd 
file_name = 'nursery.data'
df=pd.read_csv(file_name)
b= pd.DataFrame(df)
b.head(5)

usual  proper  complete  1  convenient convenient.1        nonprob  \
0  usual  proper  complete  1  convenient   convenient        nonprob   
1  usual  proper  complete  1  convenient   convenient        nonprob   
2  usual  proper  complete  1  convenient   convenient  slightly_prob   
3  usual  proper  complete  1  convenient   convenient  slightly_prob   
4  usual  proper  complete  1  convenient   convenient  slightly_prob   

   recommended  recommend  
0     priority   priority  
1    not_recom  not_recom  
2  recommended  recommend  
3     priority   priority  
4    not_recom  not_recom

In [43]:
print("Size of dataset: ", b.shape)
print("Info of dataset: ")
b.info()
print("Describe Dataset: ")
b.describe()
duplicate = b[b.duplicated()] 
duplicate
b.isnull().sum()



Size of dataset:  (12959, 9)
Info of dataset: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12959 entries, 0 to 12958
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   usual         12959 non-null  object
 1   proper        12959 non-null  object
 2   complete      12959 non-null  object
 3   1             12959 non-null  object
 4   convenient    12959 non-null  object
 5   convenient.1  12959 non-null  object
 6   nonprob       12959 non-null  object
 7   recommended   12959 non-null  object
 8   recommend     12959 non-null  object
dtypes: object(9)
memory usage: 911.3+ KB
Describe Dataset: 


not_recom     4320
priority      4266
spec_prior    4044
very_recom     328
recommend        1
Name: recommend, dtype: int64

In [5]:
a=b.values
X=a[:,:7]   
y=a[:,-1]
print(X[1])
print(y)


['usual' 'proper' 'complete' '1' 'convenient' 'convenient' 'nonprob']
['priority' 'not_recom' 'recommend' ... 'spec_prior' 'spec_prior'
 'not_recom']


In [6]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
X[:,0]= LE.fit_transform(X[:,0])
X[:,1]= LE.fit_transform(X[:,1])
X[:,2]= LE.fit_transform(X[:,2])
X[:,3]= LE.fit_transform(X[:,3])
X[:,4]= LE.fit_transform(X[:,4])
X[:,5]= LE.fit_transform(X[:,5])
X[:,6]= LE.fit_transform(X[:,6])
y= LE.fit_transform(y)




In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
scaler.fit(X)
X_scale=scaler.transform(X)
print(X)

[[2 3 0 ... 0 0 0]
 [2 3 0 ... 0 0 0]
 [2 3 0 ... 0 0 2]
 ...
 [0 4 2 ... 1 1 1]
 [0 4 2 ... 1 1 1]
 [0 4 2 ... 1 1 1]]


In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)


In [12]:
from sklearn.svm import SVC # SVM 
svclassifier = SVC(C=1,kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1, kernel='linear')

In [13]:
y_pred = svclassifier.predict(X_test)


In [14]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,zero_division=0))

[[ 70 418 350   0]
 [ 86 511 288   0]
 [ 68 222 502   0]
 [  7  68   2   0]]
              precision    recall  f1-score   support

           0       0.30      0.08      0.13       838
           1       0.42      0.58      0.49       885
           3       0.44      0.63      0.52       792
           4       0.00      0.00      0.00        77

    accuracy                           0.42      2592
   macro avg       0.29      0.32      0.28      2592
weighted avg       0.38      0.42      0.37      2592



In [16]:
Y1 = LE.inverse_transform(y_test)
Y2 = LE.inverse_transform(y_pred)
df=pd.DataFrame({'Actual':Y1, 'Predicted':Y2})
df

Actual   Predicted
0      not_recom    priority
1       priority    priority
2      not_recom  spec_prior
3       priority  spec_prior
4       priority    priority
...          ...         ...
2587  spec_prior  spec_prior
2588  spec_prior  spec_prior
2589    priority    priority
2590   not_recom    priority
2591    priority    priority

[2592 rows x 2 columns]

In [35]:
from sklearn.naive_bayes import BernoulliNB  # NB
model = BernoulliNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)


print(classification_report(y_test,y_pred,zero_division=0))



Predict of LR model:  [1. 1. 3. ... 1. 3. 1.]
Result:  [0. 1. 0. ... 1. 0. 1.]
Probability: 45.29%              precision    recall  f1-score   support

         0.0       0.32      0.14      0.20       838
         1.0       0.44      0.69      0.54       885
         3.0       0.53      0.56      0.55       792
         4.0       0.00      0.00      0.00        77

    accuracy                           0.45      2592
   macro avg       0.32      0.35      0.32      2592
weighted avg       0.42      0.45      0.41      2592



In [36]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

print(classification_report(y_test,y_pred,zero_division=0))


Predict of LR model:  [0. 1. 1. ... 1. 0. 0.]
Result:  [0. 1. 0. ... 1. 0. 1.]
Probability: 32.52%              precision    recall  f1-score   support

         0.0       0.13      0.15      0.14       838
         1.0       0.44      0.41      0.42       885
         3.0       0.46      0.45      0.46       792
         4.0       0.00      0.00      0.00        77

    accuracy                           0.33      2592
   macro avg       0.26      0.25      0.25      2592
weighted avg       0.33      0.33      0.33      2592



In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(classification_report(y_test,y_pred,zero_division=0))


Predict of LR model:  [1. 1. 3. ... 1. 1. 1.]
Result:  [0. 1. 0. ... 1. 0. 1.]
Probability: 42.32%              precision    recall  f1-score   support

         0.0       0.31      0.17      0.22       838
         1.0       0.43      0.56      0.48       885
         3.0       0.47      0.58      0.52       792
         4.0       0.00      0.00      0.00        77

    accuracy                           0.42      2592
   macro avg       0.30      0.33      0.31      2592
weighted avg       0.39      0.42      0.40      2592



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [41]:
from sklearn.neural_network import MLPClassifier

model_MLP = MLPClassifier(activation='tanh', hidden_layer_sizes=(100, 50), max_iter=300)
model_MLP.fit(X_train, y_train)
predict_MLP = model_MLP.predict(X_test)

print(classification_report(y_test,y_pred,zero_division=0))

              precision    recall  f1-score   support

         0.0       0.31      0.17      0.22       838
         1.0       0.43      0.56      0.48       885
         3.0       0.47      0.58      0.52       792
         4.0       0.00      0.00      0.00        77

    accuracy                           0.42      2592
   macro avg       0.30      0.33      0.31      2592
weighted avg       0.39      0.42      0.40      2592

