In [17]:
import pandas as pd 
import numpy as np 

In [18]:
filename = 'adult.data'
df = pd.read_csv(filename)
print(df.shape)
print(df.head(1))

(32560, 15)
   39          State-gov   77516   Bachelors  ...   0  40   United-States   <=50K
0  50   Self-emp-not-inc   83311   Bachelors  ...   0  13   United-States   <=50K

[1 rows x 15 columns]


In [19]:
print(df.dtypes)

39                 int64
 State-gov        object
 77516             int64
 Bachelors        object
 13                int64
 Never-married    object
 Adm-clerical     object
 Not-in-family    object
 White            object
 Male             object
 2174              int64
 0                 int64
 40                int64
 United-States    object
 <=50K            object
dtype: object


In [28]:
X = df.values[:,:-1]
y = df.values[:,-1]
print(X)
print(y)

[[50 ' Self-emp-not-inc' 83311 ... 0 13 ' United-States']
 [38 ' Private' 215646 ... 0 40 ' United-States']
 [53 ' Private' 234721 ... 0 40 ' United-States']
 ...
 [58 ' Private' 151910 ... 0 40 ' United-States']
 [22 ' Private' 201490 ... 0 20 ' United-States']
 [52 ' Self-emp-inc' 287927 ... 0 40 ' United-States']]
[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' >50K']


In [29]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for i in range(X.shape[1]):
    X[:,i] = encoder.fit_transform(X[:,i])
print(X)

[[33 6 2925 ... 0 12 39]
 [21 4 14085 ... 0 39 39]
 [36 4 15335 ... 0 39 39]
 ...
 [41 4 7882 ... 0 39 39]
 [5 4 12880 ... 0 19 39]
 [35 5 17824 ... 0 39 39]]


In [30]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
X = minmax.fit_transform(X)

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(\
    X, y, test_size=0.3, random_state=42)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(22792, 14)
(22792,)
Test:
(9768, 14)
(9768,)


In [32]:
# ví dụ về sử dụng SVM 
from sklearn import svm 
model = svm.SVC(kernel='linear',gamma=1e3, C=100.)
model.fit(X_train, y_train)

SVC(C=100.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1000.0, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [34]:
y_pred = model.predict(X_test)
print(y_pred)
print(y_test)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' <=50K']
[' <=50K' ' <=50K' ' >50K' ... ' <=50K' ' <=50K' ' <=50K']
