In [92]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [93]:
from google.colab import files
uploaded = files.upload()

Saving tae_demo.data to tae_demo.data
Saving tae_first.data to tae_first.data


In [94]:
# 1. Trợ giảng có phải là người nói tiếng Anh bản ngữ hay không (nhị phân); 1 = người nói tiếng Anh, 2 = người không nói tiếng Anh
# 2. Người hướng dẫn khóa học (phân loại, 25 danh mục)
# 3. Khóa học (phân loại, 26 danh mục)
# 4. Học kỳ hè hoặc học kỳ chính quy (nhị phân) 1 = Mùa hè, 2 = Thường xuyên
# 5. Sĩ số (số)
# 6. Thuộc tính lớp (phân loại) 1 = Thấp, 2 = Trung bình, 3 = Cao

import pandas as pd
import io

dataframe = pd.read_csv(io.StringIO(uploaded['tae_demo.data'].decode('utf-8')), names=["EngSpeaker", "Instructor", "Course", "Semester", "Size", "Attribute"])
dataframe


EngSpeaker  Instructor  Course  Semester  Size  Attribute
0             1          23       3         1    19          3
1             2          15       3         1    17          3
2             1          23       3         2    49          3
3             1           5       2         2    33          3
4             2           7      11         2    55          3
..          ...         ...     ...       ...   ...        ...
145           2          23       3         2    24          1
146           2           3       2         2    26          1
147           2          10       3         2    12          1
148           1          18       7         2    48          1
149           2          22       1         2    51          1

[150 rows x 6 columns]

In [95]:
engSpeaker=dataframe.loc[:, "EngSpeaker"]
engSpeaker=np.array([engSpeaker])
print(engSpeaker.shape)
engSpeaker

(1, 150)


array([[1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2,
        2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1,
        1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2,
        2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2]])

In [96]:
instructor=dataframe.loc[:,"Instructor"]
instructor=np.array([instructor])
print(instructor.shape)
instructor

(1, 150)


array([[23, 15, 23,  5,  7, 23,  9, 10, 22, 15, 10, 13, 18,  6,  6,  6,
         7, 22, 13,  7, 25, 25,  2,  1, 15,  7,  8, 14, 21, 22, 11, 18,
        13, 13,  5, 16,  4,  5, 14, 23, 15, 23,  5,  7, 23,  9, 10, 22,
        15, 10, 13, 18,  6,  6,  6,  7, 22, 13,  7, 25, 25,  2,  1, 15,
         7,  8, 14, 21, 22, 11, 18, 13, 13,  5, 16,  4,  5, 14, 23, 13,
        16,  9, 13, 18, 22,  7, 23, 23, 23, 14, 17,  9, 18, 17,  1,  1,
        11, 22,  9, 13,  6, 23, 23,  6, 22, 20, 23, 20, 23, 13, 10,  7,
        14,  8, 12,  8, 15, 23,  2, 15, 20, 13,  9, 10, 14, 13,  8, 20,
        22, 18, 20, 17, 14, 24,  9, 12,  9, 22,  7, 10, 23, 17, 16,  3,
        19, 23,  3, 10, 18, 22]])

In [97]:
course=dataframe.loc[:,"Course"]
course=np.array([course])
print(course.shape)
course

(1, 150)


array([[ 3,  3,  3,  2, 11,  3,  5,  3,  3,  3, 22,  1, 21, 17, 17, 17,
        11,  3,  3, 25,  7,  7,  9, 15, 13, 11,  3, 15,  2,  3,  1,  5,
         1,  3,  2,  8, 16,  2, 15,  3,  3,  3,  2, 11,  3,  5,  3,  3,
         3, 22,  1, 21, 17, 17, 17, 11,  3,  3, 25,  7,  7,  9, 15, 13,
        11,  3, 15,  2,  3,  1,  5,  1,  3,  2,  8, 16,  2, 15,  3,  3,
        19,  2,  3, 21,  3, 11,  3,  3,  3, 22, 17,  5, 25, 17, 15,  8,
        16, 13,  2,  1, 17,  3,  3, 17,  3,  2,  3,  2,  3,  1,  3, 11,
        15,  3,  7,  7,  1,  3,  9,  1,  2, 14,  6,  3, 15,  1,  3,  2,
         1, 12, 15, 18, 23, 26, 24,  8,  6,  1, 11,  3,  3, 18, 20,  2,
         4,  3,  2,  3,  7,  1]])

In [98]:
semester=dataframe.loc[:,"Semester"]
semester=np.array([semester])
print(semester.shape)
semester

(1, 150)


array([[1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
        2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2,
        1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [99]:
size=dataframe.loc[:,"Size"]
size=np.array([size])
print(size.shape)
size

(1, 150)


array([[19, 17, 49, 33, 55, 20, 19, 27, 58, 20,  9, 30, 29, 39, 42, 43,
        10, 46, 10, 42, 27, 23, 31, 22, 37, 13, 24, 38, 42, 28, 51, 19,
        31, 13, 37, 36, 21, 48, 38, 19, 17, 49, 33, 55, 20, 19, 27, 58,
        20,  9, 30, 29, 39, 42, 43, 10, 46, 10, 42, 27, 23, 31, 22, 37,
        13, 24, 38, 42, 28, 51, 19, 31, 13, 37, 36, 21, 48, 38, 25, 17,
        11, 39, 11, 19, 45, 20, 20, 20, 38, 17, 19, 24, 25, 31, 31, 18,
        22, 27, 14, 20, 35, 20, 20, 37, 15, 25, 10, 14, 38, 29, 19, 30,
        32, 27, 34, 23, 66, 12, 29, 19,  3, 17,  7, 21, 36, 54, 29, 45,
        11, 16, 18, 44, 17, 21, 20, 24,  5, 42, 30, 19, 11, 29, 15, 37,
        10, 24, 26, 12, 48, 51]])

In [103]:
attribute=dataframe.loc[:,"Attribute"]
attribute=np.array([attribute])
print(attribute.shape)
attribute

(1, 150)


array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [105]:
engSpeaker=engSpeaker.T #đảo dòng thành cột
instructor=instructor.T
course=course.T
semester=semester.T

print(engSpeaker.shape)
print(instructor.shape)
print(course.shape)
print(semester.shape)

X = np.concatenate((engSpeaker, instructor, course, semester),axis=1)
print(X.shape)
print(X)

(150, 1)
(150, 1)
(150, 1)
(150, 1)
(150, 4)
[[ 1 23  3  1]
 [ 2 15  3  1]
 [ 1 23  3  2]
 [ 1  5  2  2]
 [ 2  7 11  2]
 [ 2 23  3  1]
 [ 2  9  5  2]
 [ 2 10  3  2]
 [ 1 22  3  1]
 [ 2 15  3  1]
 [ 2 10 22  2]
 [ 2 13  1  2]
 [ 2 18 21  2]
 [ 2  6 17  2]
 [ 2  6 17  2]
 [ 2  6 17  2]
 [ 2  7 11  2]
 [ 2 22  3  2]
 [ 2 13  3  1]
 [ 2  7 25  2]
 [ 2 25  7  2]
 [ 2 25  7  2]
 [ 2  2  9  2]
 [ 2  1 15  1]
 [ 2 15 13  2]
 [ 2  7 11  2]
 [ 2  8  3  2]
 [ 2 14 15  2]
 [ 2 21  2  2]
 [ 2 22  3  2]
 [ 2 11  1  2]
 [ 2 18  5  2]
 [ 2 13  1  2]
 [ 1 13  3  1]
 [ 2  5  2  2]
 [ 2 16  8  2]
 [ 2  4 16  2]
 [ 2  5  2  2]
 [ 2 14 15  2]
 [ 1 23  3  1]
 [ 2 15  3  1]
 [ 1 23  3  2]
 [ 1  5  2  2]
 [ 2  7 11  2]
 [ 2 23  3  1]
 [ 2  9  5  2]
 [ 2 10  3  2]
 [ 1 22  3  2]
 [ 2 15  3  1]
 [ 2 10 22  2]
 [ 2 13  1  2]
 [ 2 18 21  2]
 [ 2  6 17  2]
 [ 2  6 17  2]
 [ 2  6 17  2]
 [ 2  7 11  2]
 [ 2 22  3  2]
 [ 2 13  3  1]
 [ 2  7 25  2]
 [ 2 25  7  2]
 [ 2 25  7  2]
 [ 2  2  9  2]
 [ 2  1 15  1]
 [ 2 15 13

In [112]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=80)
#training
attribute=attribute.T
print(attribute.shape)
model.fit(X,attribute)

(150, 1)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=80, p=2,
                     weights='uniform')

In [113]:
X_test = np.array([[2,2,10,2]])
Y_pred=model.predict(X_test)
print(Y_pred)

[1]


In [117]:
from sklearn.neighbors import KNeighborsClassifier
model12 = KNeighborsClassifier(n_neighbors=80)
#training
size=size.T
print(size.shape)
model12.fit(X,size)

(150, 1)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=80, p=2,
                     weights='uniform')

In [121]:
size_pred = model12.predict(X_test)
print(size_pred)

[37]
